include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    avoid_catches_without_on_clauses: false
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "*/generated/intl/*.dart"
    - "*/generated/*.dart"
  errors:
    invalid_annotation_target: ignore